---
title: ""
output:
  html_document:
    includes:
      in_header: hero-image.html
      after_body: footer.html
    toc: true
    toc_float:
      collapse: true
---

<!--html_preserve-->

<script async src="https://www.googletagmanager.com/gtag/js?id=G-RZPE2D0C48"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-RZPE2D0C48');
</script>

<!--/html_preserve-->

## 新型コロナワクチンの有効性

<br>

### [Vaccine Effectiveness Real-Time Surveillance for SARS-CoV-2 (VERSUS) Study、第4報](https://covid-19-japan-epi.github.io/output/ve_nagasaki_v4.html)

掲載日：2022年3月25日

**著者**

前田　遥、森本浩之輔（長崎大学熱帯医学研究所）

**要約**

 長崎大学熱帯医学研究所を中心とする研究チームは、全国の医療機関 （病院および診療所）と協力し、新型コロナワクチンの発症予防における有効性を評価する研究を2021年7月1日から開始した。今回、新型コロナウイルスの変異株B.1.1.529 系統 （オミクロン株）が全国で拡大した2022年1月1日から2月28日に新型コロナウイルス検査を受けた患者情報を用いて、この期間の発症予防における新型コロナワクチンの有効性について暫定値をまとめた。
16歳～64歳において、ファイザー社製あるいはモデルナ社製いずれかのワクチンの2回接種完了
（2回接種後14日以上経過）による発症予防における有効性を42.8% (95%信頼区間：23.6～57.1%）、3回接種完了 （3回接種後14日以上経過）における有効性を68.7% (95%信頼区間：37.1～84.4%)と推定した。2回接種完了による有効性について、ファイザー社製ワクチンに限定すると41.8% (95%信頼区間：21.1～57.1%)、モデルナ社製ワクチンに限定すると46.4% (95%信頼区間：24.1～62.2%)と推定した。2回接種完了群においてワクチン接種からの時間経過でわけて解析したところ、接種完了後から90日以内の有効性は41.4% (95%信頼区間：16.2～59.0%)、91～180日では43.0% (95%信頼区間：22.6～58.0%)、181日以降では31.7% (95%信頼区間：-17.6～60.4%)であり、時間経過とともにワクチンの有効性が減弱している可能性があると考えられた。本研究の第2報で報告した、デルタ株が流行した2021年7月1日から9月30日における発症予防における有効性と比較したところ、接種からの時間経過を加味しても新型コロナワクチンの有効性は低下していると考えられ、オミクロン株への置き換わりによる有効性の低下と考えた。
本報告は極めてサンプルサイズが限られているが、公衆衛生学的意義を鑑みつつ、暫定値を報告した。本報告は長期サーベイランス研究の一部であり、2022年1月1日から2月28日においても、集計できていない情報もあるため、今後結果が変わる可能性があり、随時アップデートした結果を報告する予定である。

<br>

### [Vaccine Effectiveness Real-Time Surveillance for SARS-CoV-2 (VERSUS) Study、第3報](https://covid-19-japan-epi.github.io/output/ve_nagasaki_v3.html)

掲載日：2022年1月26日

**著者**

前田　遥、森本浩之輔（長崎大学熱帯医学研究所）

**要約**

 長崎大学熱帯医学研究所を中心とする研究チームは、全国の医療機関（病院および診療所）と協力し、新型コロナワクチンの有効性を評価する研究を2021年7月1日から開始した。今回、新型コロナウイルスの変異株B.1.1.529 系統（オミクロン株）が全国で広がり始めた2022年1月1日以降に新型コロナウイルス検査を受けた患者情報を用いて、この期間の発症予防における新型コロナワクチンの有効性について暫定値をまとめた。16歳～64歳において、ファイザー社製あるいはモデルナ社製いずれかのワクチンの2回接種完了（2回接種後14日以上経過）による発症予防における有効性を51.7% (95%信頼区間：2.0～76.2%） と推定した。デルタ株が流行した2021年7月1日から9月30日における同値は88.7% (95%信頼区間：78.8%～93.9%)であり、新型コロナワクチンの有効性は低下していると考えられた。
 本報告は極めてサンプルサイズが限られているが、公衆衛生学的意義を鑑みつつ、暫定値を報告した。本報告は長期サーベイランス研究の一部であり、随時アップデートした結果を報告する予定である。

<br>

### [Vaccine Effectiveness Real-Time Surveillance for SARS-CoV-2 (VERSUS) Study、第2報](https://covid-19-japan-epi.github.io/output/ve_nagasaki_v2.html)

掲載日：2021年12月1日

最終版掲載日：2022年2月2日

**著者**

前田　遥、森本浩之輔（長崎大学熱帯医学研究所 臨床研究部門）

**要約**

長崎大学熱帯医学研究所を中心とする研究チームは、全国の医療機関 （病院および診療所）と協力し、新型コロナワクチンの発症予防における有効性を評価する研究を2021年7月1日から開始した。今回、2021年7月1日～9月30日の登録患者情報を用いて結果をまとめた。16歳～64歳において2回接種完了 （2回目接種後14日以上経過）による発症予防における有効性は、ファイザー社製あるいはモデルナ社製いずれかのワクチンでは88.7% (95%信頼区間：78.8～93.9%)、ファイザー社製ワクチンに限定すると86.7% (95%信頼区間：73.5～93.3%)、モデルナ社製ワクチンに限定すると96.6% (95%信頼区間：72.8～99.6%)と推定された。65歳以上においては、ファイザー社製あるいはモデルナ社製いずれかのワクチンの2回接種完了による発症予防における有効性は90.3% (95%信頼区間：73.6～96.4%)、ファイザー社製ワクチンに限定すると85.8% (95%信頼区間：59.4～95.0%)と推定された。今回、ワクチン接種後の時間経過による有効性の減弱を評価することを目的として、16歳～64歳において、ファイザー社製あるいはモデルナ社製ワクチン2回接種完了後1～3か月と4～6か月でわけた解析を実施した。その結果、発症予防における有効性はワクチン2回接種完了後1～3か月で91.8% (95%信頼区間：80.3～96.6%)、4～6か月で86.4% (95%信頼区間：56.9～95.7%)と推定された。
本報告は長期サーベイランス研究の一部であり、10月以降も研究は継続しており、随時アップデートした結果を報告する予定である。なお、長期サーベイランスを行うことで、接種後からの時間経過、ブースター接種や変異株によってワクチンの有効性がどのように変動するかを評価する予定である。

<br>

### [Vaccine Effectiveness Real-Time Surveillance for SARS-CoV-2 (VERSUS) Study、第1報](https://covid-19-japan-epi.github.io/output/新型コロナワクチンの有効性研究.html)

掲載日：2021年10月5日

**著者**

前田　遥、森本浩之輔（長崎大学熱帯医学研究所 臨床研究部門）

**要約**

現在、国内において実臨床上での新型コロナワクチンの有効性を評価した研究は十分ではない。長崎大学熱帯医学研究所を中心とする研究チームは、全国の医療機関（病院および診療所）と協力し、新型コロナワクチンの有効性を評価する研究を2021年7月1日から開始した。2021年7月1日～8月31日のデータを用いて暫定結果をまとめたところ、16歳～64歳において、ファイザー社製あるいはモデルナ社製いずれかのワクチンの2回接種による発症予防における有効性は86.8%(95%信頼区間：71.0～94.0%)、ファイザー社製ワクチンに限定すると、2回接種による発症予防における有効性は85.6%(95%信頼区間：67.6～93.6%)と推定された。本報告は長期サーベイランス研究の一部であり、9月以降も研究は継続しており、随時アップデートした結果を報告する予定である。なお、長期サーベイランスを行うことで、変異株やブースター接種によってワクチンの有効性がどのように変動するかを評価する予定である。

<br>

